apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 10m
  chart:
    spec:
      chart: jenkins
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: jenkins
  values:
    namespaceOverride: "jenkins"
    clusterZone: "plutolab.live"
    persistence:
      enabled: true
      accessModes: "ReadWriteOnce"
      size: 60Gi