apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets-operator
resources:
  - namespace.yaml
  - issuer/cluster-issuer.yaml
  - issuer/certificate.yaml
  - helm.yaml