apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/traefik

configMapGenerator:
  - name: traefik-values
    namespace: traefik
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml

patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: traefik
      namespace: traefik
    spec:
      valuesFrom:
        - kind: ConfigMap
          name: traefik-values
          valuesKey: values.yaml