apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  interval: 10m0s
  path: ./infrastructure/swanson/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/swanson/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  interval: 10m0s
  path: ./infrastructure/swanson/external-secrets/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-issuers
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitwarden-secrets-manager
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  interval: 10m0s
  path: ./infrastructure/swanson/external-secrets/bitwarden-secrets-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-operator
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: flux-system
spec:
  targetNamespace: cloudflare-tunnel-ingress-controller
  interval: 10m0s
  path: ./infrastructure/swanson/cloudflare-tunnel-ingress-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: bitwarden-secrets-manager
  wait: true
  timeout: 5m