apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: external-secrets
resources:
  - namespace.yaml
  - bitwarden-secrets-manager/issuer/cluster-issuer.yaml
  - bitwarden-secrets-manager/issuer/certificate.yaml
  - helm.yaml
  - bitwarden-secrets-manager/bitwarden-credentials.sops.yaml
  - bitwarden-secrets-manager/clustersecretstore.yaml
configMapGenerator:
  - name: external-secrets-values
    files:
      - values.yaml=values.yaml