apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patches:
  - patch: |
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: not-used
      spec:
        decryption:
          provider: sops
          secretRef:
            name: sops-gpg
    target:
      kind: Kustomization
      labelSelector: "!excludeFromPatches"