apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/longhorn
  
patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: longhorn
      namespace: longhorn-system
    spec:
      values:
        defaultSettings:
          defaultDataPath: /var/mnt/storage-volume
          storageReservedPercentageForDefaultDisk: 10
  - |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: longhorn-system
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
