apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: skywalker-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.202.102-192.168.202.104
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: skywalker-ip-pool-advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - skywalker-ip-pool
