apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: skynet-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.203.44/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: skynet-ip-pool-advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - skynet-ip-pool