apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: blog-repository
  namespace: flux-system
spec:
  image: ghcr.io/talhajuikar/talhajuikar.github.io
  interval: 1m0s
  secretRef:
    name: blog-website-ghcr