apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prism-element-secret
  namespace: ntnx-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ntnx-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        endpoint: "{{ .endpoint }}"
  data:
    - secretKey: endpoint
      remoteRef:
        key: "76266dd3-1675-4279-8226-b2df0076799f"