apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: cloudflare-tunnel-ingress-controller
resources:
  - namespace.yaml
  - externalsecret.yaml
  - repository.yaml
  - release.yaml