apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- repository.yaml
- release.yaml
- ingressroute.yaml

configMapGenerator:
  - name: infra-services-dashboard
    files:
      - ../dashboards/traefik.json
      - ../dashboards/harbor.json
      - ../dashboards/cloudnative-pg.json
    options:
      labels:
        grafana_dashboard: "1"