apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel-ingress-controller
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-secret
    creationPolicy: Owner
  data:
    - secretKey: accountId
      remoteRef:
        key: "fab5ec54-0f51-493a-9e79-b2dd008f2f20"
    - secretKey: tunnelName
      remoteRef:
        key: "894badca-76ba-4918-addd-b2dd00998529"
    - secretKey: apiToken
      remoteRef:
        key: "23d50bb2-21f0-4d9c-96f9-b2dd008f10e2"
