apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: cloudflare-tunnel-ingress-controller
spec:
  driftDetection:
    mode: enabled
  interval: 10m
  chart:
    spec:
      chart: cloudflare-tunnel-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: strrl.dev
  values:
    cloudflare:
      secretRef:
        name: cloudflare-tunnel-secret
        accountIDKey: accountId
        tunnelNameKey: tunnelName
        apiTokenKey: apiToken