clusterName: ricky
endpoint: https://192.168.203.83:6443
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: none
allowSchedulingOnMasters: true
allowSchedulingOnControlPlanes: true
nodes:
  - hostname: talos01
    ipAddress: 192.168.203.17
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: ens18
        addresses:
          - 192.168.203.17/22
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.200.1
        vip:
          ip: 192.168.203.83

  - hostname: talos02
    ipAddress: 192.168.203.18
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: ens18
        addresses:
          - 192.168.203.18/22
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.200.1
        vip:
          ip: 192.168.203.83

  - hostname: talos03
    ipAddress: 192.168.203.19
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: ens18
        addresses:
          - 192.168.203.19/22
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.200.1
        vip:
          ip: 192.168.203.83

  # - hostname: talos-worker1
  #   ipAddress: 192.168.203.20
  #   installDisk: /dev/sda
  #   controlPlane: false
  #   networkInterfaces:
  #     - interface: ens18
  #       addresses:
  #         - 192.168.203.20/22
  #       routes:
  #         - network: 0.0.0.0/0
  #           gateway: 192.168.200.1

  # - hostname: talos-worker2
  #   ipAddress: 192.168.203.21
  #   installDisk: /dev/sda
  #   controlPlane: false
  #   networkInterfaces:
  #     - interface: ens18
  #       addresses:
  #         - 192.168.203.21/22
  #       routes:
  #         - network: 0.0.0.0/0
  #           gateway: 192.168.200.1


  # - hostname: talos-worker3
  #   ipAddress: 192.168.203.22
  #   installDisk: /dev/sda
  #   controlPlane: false
  #   networkInterfaces:
  #     - interface: ens18
  #       addresses:
  #         - 192.168.203.22/22
  #       routes:
  #         - network: 0.0.0.0/0
  #           gateway: 192.168.200.1

controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools
          - siderolabs/util-linux-tools
  certSANs:
    - 192.168.203.83
  nameservers:
    - 192.168.202.2
    - 8.8.8.8
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          rotate-server-certificates: "true"
    - |-
      - op: add
        path: /machine/kubelet/extraMounts
        value:
          - destination: /var/mnt/storage-volume
            type: bind
            source: /var/mnt/storage-volume
            options:
              - bind
              - rshared
              - rw
  userVolumes:
    - name: storage-volume
      provisioning:
        diskSelector:
          match: 'disk.size > 280u * GB && disk.size < 340u * GB && !system_disk'
        minSize: "290GiB"
        maxSize: "310GiB"
      filesystem:
        type: ext4

# worker:
#   schematic:
#     customization:
#       extraKernelArgs:
#         - net.ifnames=0
#   nameservers:
#     - 192.168.202.2
#     - 8.8.8.8
#   extraManifests:
#     - kubelet-serving-cert-approver.yaml
#     - metrics-server.yaml
#   patches:
#     - |-
#       - op: add
#         path: /machine/kubelet/extraArgs
#         value:
#           rotate-server-certificates: "true"