apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  targetNamespace: longhorn-system
  interval: 10m0s
  path: ./infrastructure/ricky/longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system