apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-container-registry-credentials
  namespace: portfolio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: blog-website-ghcr
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: "cef77024-b608-4f74-9381-b2de00738288"
        property: "dockerconfig"
