apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nutanix-csi-storage
  namespace: ntnx-system
spec:
  interval: 10m
  # dependsOn:
  #   - name: snapshot-controller
  #     namespace: nutanix-csi
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: nutanix-csi-storage
      version: 2.6.10
      sourceRef:
        kind: HelmRepository
        name: nutanix-repo
