apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  driftDetection:
    mode: enabled
  interval: 10m
  chart:
    spec:
      chart: reflector
      version: 9.1.7
      sourceRef:
        kind: HelmRepository
        name: emberstack