apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: it-tools
  name: it-tools
  namespace: it-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-tools
  strategy: {}
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
      - image: corentinth/it-tools:latest
        name: it-tools
        ports:
        - containerPort: 80
        resources: {
          "limits": {
            "cpu": "300m",
            "memory": "512Mi"
          },
          "requests": {
            "cpu": "100m",
            "memory": "128Mi"
          }
        }
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: it-tools
  name: it-tools
  namespace: it-tools
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: it-tools
  type: ClusterIP
status: {}
