apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: it-tools
  namespace: it-tools
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml