apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: it-tools
  namespace: it-tools
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml