apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/traefik

configMapGenerator:
  - name: traefik-values
    namespace: traefik
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - path: hr-patch.yaml