apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/longhorn
  
patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: longhorn
      namespace: longhorn-system
    spec:
      values:
        persistence:
          defaultClass: false
        defaultSettings:
          defaultDataPath: /mnt/longhorn
          storageReservedPercentageForDefaultDisk: 10