apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/traefik

configMapGenerator:
  - name: traefik-values
    namespace: traefik
    behavior: merge
    files:
      - values.yaml=values-patch.yaml