# Custom values for Morpheus cluster
service:
  spec:
    loadBalancerIP: 192.168.201.232

deployment:
  enabled: true
  replicas: 3
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

tlsStore:
  default:
    defaultCertificate:
      secretName: plutolab-live-tls

metrics:
  prometheus:
    service:
      enable: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus

logs:
  general:
    format: "json"
    level: "INFO"
    filePath: ""
    noColor: false
  access:
    enabled: true
    format: "json"
    bufferingSize:
    filters:
      statuscodes: "400-499,500-599"
      retryattempts: false
      minduration: ""
    addInternals: false
    fields:
      general:
        defaultmode: keep
        names: {}
      headers:
        defaultmode: drop
        names: {}