# Custom values for Morpheus cluster
service:
  spec:
    loadBalancerIP: 192.168.201.232

deployment:
  enabled: true
  replicas: 3
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

tlsStore:
  default:
    defaultCertificate:
      secretName: plutolab-live-tls