apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/rancher

configMapGenerator:
  - name: rancher-values
    namespace: cattle-system
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml

patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: rancher
      namespace: cattle-system
    spec:
      valuesFrom:
        - kind: ConfigMap
          name: rancher-values
          valuesKey: values.yaml