apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  driftDetection:
    mode: enabled
  interval: 30m
  chart:
    spec:
      chart: loki
      version: "6.30.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h