apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml

configMapGenerator:
  - name: traefik-values
    namespace: traefik
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml