apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kubelet-serving-cert-approver
  namespace: kubelet-serving-cert-approver
resources:
  - kubelet-serving-cert-approver.yaml