apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: it-tools
  namespace: flux-system
spec:
  targetNamespace: it-tools
  interval: 10m0s
  path: ./apps/skywalker/it-tools
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  targetNamespace: jellyfin
  interval: 10m0s
  path: ./apps/skywalker/jellyfin
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/skywalker/authentik
  targetNamespace: authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: bitwarden-secrets-manager
  wait: true
  timeout: 5m