apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-serving-cert-approver
  namespace: flux-system
spec:
  targetNamespace: kubelet-serving-cert-approver
  interval: 10m0s
  path: ./apps/skywalker/kubelet-serving-cert-approver
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  targetNamespace: kube-system
  interval: 10m0s
  path: ./apps/skywalker/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system