apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metallb
  namespace: metallb-system
resources:
  - namespace.yaml
  - github.com/metallb/metallb/config/native?ref=v0.14.9