apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk.external-secrets.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            name: bitwarden-credentials
            namespace: external-secrets
            key: access-token
      # Reference secrets using the correct format for secret references
      organizationID: 
        name: bitwarden-credentials
        namespace: external-secrets
        key: organization-id
      projectID:
        name: bitwarden-credentials
        namespace: external-secrets
        key: project
      # For CA certificate, use correct reference format
      caProvider:
        name: bitwarden-ca-cert
        namespace: external-secrets
        key: ca.crt