apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk.external-secrets.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            name: bitwarden-credentials
            namespace: external-secrets
            key: access-token
      # Reference secrets for organization ID and project ID
      organizationIDSecretRef:
        name: bitwarden-credentials
        namespace: external-secrets
        key: organization-id
      projectIDSecretRef:
        name: bitwarden-credentials
        namespace: external-secrets
        key: project
      # CA certificate reference
      caBundle:
        secretRef:
          name: bitwarden-ca-cert
          namespace: external-secrets
          key: ca.crt