apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnel-ingress-controller
  namespace: flux-system
spec:
  targetNamespace: cloudflare-tunnel-ingress-controller
  interval: 10m0s
  path: ./namespaces/cloudflare-tunnel-ingress-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system