apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitwarden-secrets-manager
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  interval: 10m0s
  path: ./namespaces/external-secrets/bitwarden-secrets-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: external-secrets-operator
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
