---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-creds
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: authentik-creds
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "fe561bf8-246b-423a-8a8b-b2ed00c4388d"