apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/authentik
  - external-secret.yaml

configMapGenerator:
  - name: authentik-values
    namespace: authentik
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - path: hr-patch.yaml