authentik:
    secret_key: env://AUTHENTIK_SECRET_KEY
    error_reporting:
        enabled: false
    postgresql:
        password: env://AUTHENTIK_POSTGRESQL__PASSWORD

postgresql:
    enabled: true
    auth:
        existingSecret: authentik-creds

redis:
    enabled: true

server:
  env:
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
            name: authentik-creds
            key: password
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
            name: authentik-creds
            key: secret-key
  ingress:
      ingressClassName: traefik
      enabled: true
      hosts:
          - sso.plutolab.live
      tls:
        - secretName: plutolab-live-tls

worker:
    env:
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
                name: authentik-creds
                key: password
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
                name: authentik-creds
                key: secret-key