apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-image-test-git
  namespace: flux-system
spec:
  interval: 1m
  url: https://gitlab.plutolab.live/thanelab/flux-image-test.git
  ref:
    branch: main  # Main branch will contain all environment configurations
  secretRef:
    name: gitlab-credentials