apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  interval: 10m0s
  path: ./infrastructure/external-secrets/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system