apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn
  namespace: longhorn-system
resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - ingressroute.yaml
  - basic-auth.yaml