apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data-pvc
  namespace: actual-budget
  labels:
    app: actual-budget
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi