apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
resources:
- namespace.yaml
- helm.yaml
- grafana-repo.yaml
- loki-helm.yaml
- promtail.yaml
- ingressroute.yaml