apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/service.yaml
  - base/ingressroute.yaml
  - image-automation/image-policy.yaml
  - image-automation/image-repository.yaml
  - image-automation/image-update-automation.yaml

images:
  - name: blog-website
    newName: ghcr.io/talhajuikar/talhajuikar.github.io # {"$imagepolicy": "flux-system:blog-policy:name"}
    newTag: 1.0.31 # {"$imagepolicy": "flux-system:blog-policy:tag"}