apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 10m0s
  path: ./monitoring/default/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system