apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plutolab-live-tls
  namespace: traefik
spec:
  secretName: plutolab-live-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.plutolab.live"
  dnsNames:
  - "plutolab.live"
  - "*.plutolab.live"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default"