apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: jellyfin
resources:
  - namespace.yaml
  - config-storage.yaml
  - media-storage.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml