apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plutolab-live-tls
  namespace: traefik
spec:
  secretName: plutolab-live-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.plutolab.live"
  dnsNames:
  - "plutolab.live"
  - "*.plutolab.live"
