apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: it-tools
  namespace: flux-system
spec:
  targetNamespace: it-tools
  interval: 10m0s
  path: ./namespaces/it-tools
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: it-tools
  namespace: it-tools
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml