apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: rke2-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.201.234-192.168.201.235
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: rke2-ip-pool-advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - rke2-ip-pool
