apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: blog-auto-update
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: Flux CD Bot
      messageTemplate: "Update image tags for {{range .Updated.Images}}{{.}}{{end}}"
    push:
      branch: main
  update:
    path: ./namespaces/portfolio
    strategy: Setters