apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: newt-external-secret
  namespace: newt
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: newt-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "03c05ba2-62aa-438d-bd07-b32c00bbcbf6"
