apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: flux-image-test
  namespace: flux-system
spec:
  image: registry.gitlab.plutolab.live/thanelab/flux-image-test
  interval: 1m
  secretRef:
    name: gitlab-registry-credentials