apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/loki

configMapGenerator:
  - name: loki-values
    namespace: monitoring
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - path: hr-patch.yaml