apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/loki

configMapGenerator:
  - name: loki-values
    namespace: monitoring
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml

patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: loki
      namespace: monitoring
    spec:
      valuesFrom:
        - kind: ConfigMap
          name: loki-values
          valuesKey: values.yaml