deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: "filesystem"
  schemaConfig:
    configs:
      - from: "2020-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem
        schema: v13
  limits_config:
    retention_period: 4d
    ingestion_rate_mb: 10
    ingestion_burst_size_mb: 20
singleBinary:
  replicas: 1
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
  persistence:
    enableStatefulSetAutoDeletePVC: true
    enabled: true
    size: 10Gi
    storageClass: longhorn
monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false