apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prism-element-secret.yaml
  - ../../../base/nutanix-csi/storage

patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: nutanix-csi-storage
      namespace: ntnx-system
    spec:
      values:
        createSecret: false
        secretName: ntnx-secret
        storageContainer: morpheus-k8s
        volumeClass: true
        defaultStorageClass: volume