apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-values
      valuesKey: values.yaml