apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kube-prometheus-stack

configMapGenerator:
  - name: kube-prometheus-values
    namespace: monitoring
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml

patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    metadata:
      name: kube-prometheus
      namespace: monitoring
    spec:
      valuesFrom:
        - kind: ConfigMap
          name: kube-prometheus-values
          valuesKey: values.yaml