apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kube-prometheus-stack

configMapGenerator:
  - name: kube-prometheus-values
    namespace: monitoring
    files:
      - values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - path: namespace-patch.yaml
  - path: hr-patch.yaml