apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: it-tools
  namespace: flux-system
spec:
  targetNamespace: it-tools
  interval: 10m0s
  path: ./apps/it-tools
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
