apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-credentials
    namespace: external-secrets
type: Opaque
stringData:
    access-token: ENC[AES256_GCM,data:RPBIlwJgCwtHamXrCpp8sBhGczCIaM+mQVqsYJxjLWVJcsLe4QzIMOpPdRsNukKJHAA3gVmn1rkcMbpBwkljQ6hsW53z3KeN9Wg+Rl5Y8TQk7OLpWWyKVOzeeEABYQ==,iv:e9lxFU8Z0U5YGKmNbpyrMhcILjkoScg1kyVv3ZwYYio=,tag:/PPAIx6IXa2Xi8SlTSQCXg==,type:str]
    organization-id: ENC[AES256_GCM,data:c1jCTII7TYO2JLOyHRDwvyUnt5Xev3bujOto5dWJbIjaNeyc,iv:c+Nz+jfSjKCRZlqmfKPoHUJfiG4vM5HEmjPiS4xGHUs=,tag:jyVvN1zxtr5yWMVAlntvBQ==,type:str]
    project: ENC[AES256_GCM,data:1Sh5IZBUo0WsQ77OM7S+hpU0HpF2WtYIXlJhcnJtfxEoeYb+,iv:2E0QCbNWdsJOsI1lpqofHAK1ia9pLV3mDCfj+PVxP34=,tag:xPk1Kkmze6wFZJUTc5Vj2A==,type:str]
sops:
    lastmodified: "2025-05-13T07:54:47Z"
    mac: ENC[AES256_GCM,data:q3X4J/L8iJ+Ow4aajaqZuAvlQ7oTbEhlUHnr4oT52o4UMlsIaKflz9Bj0W7Iy51jrkWAjlTHQFbTwSfpVlUPfF6YwVaqRZLoW9DuOOkJuy0Nc/1O4HN291NW2tjM4J0zQwxdxxK46GXzy76sr84DSBI+rvE4jjzZh0bE+m0mYyM=,iv:B4OjT1vdEAAsJk04U5q6HXjbBm3pRpSIPNyqhuBAyj4=,tag:/QjVjJc9zCFWTufForo8zw==,type:str]
    pgp:
        - created_at: "2025-05-13T07:54:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwXaIPvL6sCpARAAhttDMlRtBdWwZts2w48ahMFgQXoCNlgILUun80wOeZo+
            LAeEAvWk4YOvTQAv0k+cnl1IWN4Ssr4Oc2VXzbdb8zEo3uwELewTQZMIQCcDgjm2
            uQCBhJWM62xTY4agfElqLmaZnD4Acj+/H3dny+C2nBGTNrYJt+9CGBQ8qgeCLbJz
            rgc6YKrLTI9raXEbqTyT2uZilu1WzlTdRxeW4pAaX2EWPZ0HV3i0z7fi+aQcFwoC
            YLwjwOS14Y61UfJ3BKFhcIa4Gtz7MJTNh2D/c3X3/aX6z3QBhoagLNgfIYweexkY
            PyaaCymtqaZhvzpiK/TK1yGuMKyJ5jwxJbpSG9MXmclhIJwLfIetVWBiOeTScCrD
            F+7pHbtFE8hGF+RiUAkXYmsA/nYugQZUrNNHUXxbCGM3SO/tom0217zQWN8qF0+d
            4DLShajJBzDSjsf8682QBq5DIJsL4b1Na+GodBCyd5O0wACn0YKuJWmfhcc/r52L
            ZW1gcpEvM0Sx0ml9IrMEb/X8K9YSJWfS+N290cDfPpL5Ixx+gQ3a34BVI4YgjB+6
            AnaAjRe6Od0jNuDeeSgV0nsH9UddC9tUDMDMVWb65zrHseOVubwHcVAgSoOSnlSw
            YOvPs3Q8GICP5qT8iQJ76DHcWCbl7zyIzQKNrJGSPL/ImURPWB5wFyAxOpXJxWTU
            aAEJAhBwu5WAwfuCrGiLgHh2VfDNtZjItWYEudOGKjO5MObsgJ2b8+Ka5Pne4hsK
            bsVCww3ZN2oFDd7FlG6PlOZDuyVNE6nQtakucFnXHiAb6GDV5cKJ0Ho0WCGWw0Xd
            8979mbK8rX5K
            =0MOc
            -----END PGP MESSAGE-----
          fp: CCEC75297BC309A88157665205DA20FBCBEAC0A9
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
